# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-release

on:
  push:
    branches: [ "main" ]

jobs:
  build-release-linux:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test

    - name: Create tar file
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: tar
        directory: /home/runner/.cache/tree-sitter
        path: lib/*
        filename: linux.tar.gz
        
    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: linux.tar.gz
        path: /home/runner/.cache/tree-sitter/linux.tar.gz
        if-no-files-found: error


  build-release-windows:
    runs-on: windows-latest

    permissions:
        contents: write

    steps:

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test

    - name: Create tar file
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: tar
        directory: C:\Users\runneradmin\AppData\Local\tree-sitter
        path: lib/*
        filename: windows.tar.gz

    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: windows.tar.gz
        path: C:\Users\runneradmin\AppData\Local\tree-sitter\lib\css_in_js.dll
        if-no-files-found: error


  build-release-macos:
    runs-on: macos-latest

    permissions:
        contents: write

    steps:

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test

    - name: Create tar file
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: tar
        directory: /Users/runner/Library/Caches/tree-sitter
        path: lib/*
        filename: macos.tar.gz

    - name: Upload tarball
      uses: actions/upload-artifact@v3
      with:
        name: macos.tar.gz
        path: /Users/runner/Library/Caches/tree-sitter/macos.tar.gz
        if-no-files-found: error

  generate-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    
    - name: Collect packages
      uses: actions/download-artifact@v3
      with:
        path: ~/artifacts
    - name: blorp
      run: |
        find ~/artifacts
