# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-release

on:
  push:
    branches: [ "main" ]

jobs:
  build-release-linux:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ~/.cache/tree-sitter/lib
        files: |
          css_in_js.so
        outPath: ~/linux.tar.gz


  build-release-macos:
    runs-on: macos-latest

    permissions:
        contents: write

    steps:

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: "$HOME/Library/Caches/tree-sitter/lib"
        files: |
          css_in_js.so
        outPath: "$HOME/osx.tar.gz"


  build-release-windows:
    runs-on: windows-latest

    permissions:
        contents: write

    steps:

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        dir "$HOME"
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: $HOME/AppData/Local/tree-sitter/lib
        files: |
          css_in_js.dll
        outPath: $HOME/windows.tar.gz
