# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-release

on:
  push:
    branches: [ "main" ]

jobs:
  build-release-windows:
    runs-on: windows-latest

    permissions:
        contents: write

    steps:

    - name: Configure shared-library info
      run: |
        echo LIBDIR=C:\Users\runneradmin\AppData\Local\tree-sitter\lib >> $env:GITHUB_ENV
        echo TARBALL=C:\Users\runneradmin\windows.tar.gz >> $env:GITHUB_ENV

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        echo "1. $HOME 2. ${{ env.HOME }} 3. $env:HOME"
        echo "1. $LIBDIR 2. ${{ env.LIBDIR }} 3. $env:LIBDIR"
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: $env:LIBDIR
        files: |
          css_in_js.dll
        outPath: $env:TARBALL


  build-release-linux:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
    - name: Configure shared-library info
      run: |
        echo LIBDIR=$HOME/.cache/tree-sitter/lib >> $GITHUB_ENV
        echo TARBALL=$HOME/linux.tar.gz >> $GITHUB_ENV

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ${{ env.LIBDIR }}
        files: |
          css_in_js.so
        outPath: ${{ env.TARBALL }}


  build-release-macos:
    runs-on: macos-latest

    permissions:
        contents: write

    steps:

    - name: Configure shared-library info
      run: |
        echo LIBDIR=$HOME/Library/Caches/tree-sitter/lib >> $GITHUB_ENV
        echo TARBALL=$HOME/osx.tar.gz >> $GITHUB_ENV

    - name: Get Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build and test
      run: |
        npm ci
        npm run build --if-present
        npm run test
        
    - name: Create tarball
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ${{ env.LIBDIR }}
        files: |
          css_in_js.so
        outPath: ${{ env.TARBALL }}


